#!/bin/bash
# C name
# error handling
if [ -z "$CFILE" ]; then
    echo "Error: CFILE is not set"
    exit 1
fi

# .c reverse .s
output_file="${CFILE%.c}.s"

# gcc ile assembly ceated
gcc -S "$CFILE" -o "$output_file"
